# Generated by Django 5.0.4 on 2024-04-16 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('orders', '0002_rename_name_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.profile'),
            preserve_default=False,
        ),
    ]
